# Engagement settings for conversation management

# Time-based settings
time_limits:
  max_conversation_age_hours: 24
  min_reply_interval_minutes: 5
  max_reply_interval_hours: 12
  peak_hours: [9, 21]  # 9 AM to 9 PM

# Conversation depth settings
depth_limits:
  max_replies_per_conversation: 10
  max_concurrent_conversations: 5
  min_replies_before_rest: 3

# User value thresholds
user_value:
  min_follower_count: 100
  min_engagement_rate: 0.01  # 1% engagement rate
  high_value_multipliers:
    verified: 1.5
    mutual_follow: 1.3
    previous_positive_interactions: 1.4
    expert_in_field: 1.6

# Content quality thresholds
quality_thresholds:
  min_sentiment: -0.3  # Allow slightly negative
  min_relevance: 0.6
  min_coherence: 0.7
  toxic_threshold: 0.8  # Above this is considered toxic

# Engagement scoring weights
scoring_weights:
  user_value: 0.3
  content_quality: 0.3
  timeliness: 0.2
  conversation_momentum: 0.2

# Momentum factors
momentum_factors:
  reply_speed: 0.3  # Weight for how quickly others reply
  engagement_growth: 0.4  # Weight for growing engagement
  topic_relevance: 0.3  # Weight for topic alignment

# Topic alignment
topic_weights:
  core_expertise: 1.0
  related_fields: 0.7
  general_interest: 0.4
  off_topic: 0.2

# Continuation triggers
continue_if:
  high_value_user_engaged: true
  growing_engagement: true
  trending_topic: true
  positive_sentiment_trend: true

# Termination triggers
terminate_if:
  toxic_content_detected: true
  spam_patterns_detected: true
  engagement_declining: true
  off_topic_drift: true

# Recovery settings
recovery:
  min_rest_period_minutes: 30
  engagement_cooldown_hours: 2
  max_daily_interactions: 100
